services:
  k6:
    image: grafana/k6:1.3.0
    container_name: glossary-k6
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5665:5665
    volumes:
      - ../src:/src
      - ../../proto:/proto
    environment:
      - K6_WEB_DASHBOARD=true
      - TEST_FILE=/src/tests/rest.ts
    entrypoint: ["/bin/sh", "-lc", "k6 run $${TEST_FILE}"]
