FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1 \
  PIP_DISABLE_PIP_VERSION_CHECK=1

RUN apt-get update && apt-get install -y make

WORKDIR /app

EXPOSE 8000

SHELL ["/bin/bash", "-c"]
ENTRYPOINT [ -d /venv/bin ] || python -m venv /venv && . /venv/bin/activate && pip install -r requirements.txt && make rest.develop